# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2
builds:
  - main: ./cmd/awair-exporter/awair-exporter.go

    binary: awair-exporter

    ldflags:
      - -s -w -X main.build={{.Version}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - "6"
      - "7"

    mod_timestamp: "{{ .CommitTimestamp }}"

changelog:
  use: github-native
