global:
  scrape_interval: 5s

scrape_configs:
  - job_name: awair-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:8080

  - job_name: awair
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 192.168.0.3
          - 192.168.0.4
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:8080
