{
 "title": "Awair",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Awair Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awair_score", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Awair Score",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "awair_score", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Carbon Dioxide (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "awair_co2", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Total Volatile Organic Compounds (ppb)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "awair_voc", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Particulate Matter < 2.5 microns",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "awair_pm25", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Temperature (°F)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "(awair_temp * 9/5) + 32", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "awair_humidity", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  }
 ]
}