---
name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: prepare
        id: prepare
        run: |
          DOCKER_PLATFORMS=linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          echo BUILDX_ARGS="--platform ${DOCKER_PLATFORMS} --file ./Dockerfile ./" >> $GITHUB_ENV

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Buildx (build)
        run: |
          docker buildx build --output "type=image,push=false" ${{ env.BUILDX_ARGS }}
