name: CI Pipeline

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  pre-commit-check:
    uses: ./.github/workflows/pre-commit-check.yaml@main
  go-tests:
    uses: ./.github/workflows/go-tests.yaml@main
  docker:
    uses: ./.github/workflows/docker.yaml@main
    needs: [pre-commit-check, go-tests]
    with:
      push_image: ${{ (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
