name: CI Pipeline

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  pre-commit-check:
    uses: rtrox/prometheus-awair-exporter/.github/workflows/pre-commit-check.yaml@main
  go-tests:
    uses: rtrox/prometheus-awair-exporter/.github/workflows/go-tests.yaml@main
  docker:
    uses: rtrox/prometheus-awair-exporter/.github/workflows/docker.yaml@main
    needs: [pre-commit-check, go-tests]
    with:
      push_image: ${{ (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
    secrets: inherit

  release:
    name: Release
    needs: [pre-commit-check, go-tests, docker]
    if: startsWith(github.ref, 'refs/tags/v')
    uses: rtrox/prometheus-awair-exporter/.github/workflows/release.yaml@main
    secrets: inherit
